enabled: true

steps:
  - name: start_docker
    commands:
     - start_dockerd.sh

  - name: build
    description: Build Cortex
    commands:
      - make TTY=--network=host

  - name: tag-and-push
    commands:
      - |
          export ORIGINAL_IMAGE_NAME=quay.io/cortexproject/cortex:latest
          export HS_IMAGE_NAME=docker.hubteam.com/cortex/$GIT_BRANCH
          export HS_IMAGE_NAME_BUILD_NUMBER=$HS_IMAGE_NAME:$BUILD_NUMBER
          docker tag $ORIGINAL_IMAGE_NAME $HS_IMAGE_NAME:latest
          docker tag $ORIGINAL_IMAGE_NAME $HS_IMAGE_NAME_BUILD_NUMBER
          hs-docker-push $HS_IMAGE_NAME_BUILD_NUMBER -r $HS_IMAGE_NAME -t $BUILD_NUMBER -t latest
